package pe.edu.upc.easyvet.core.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF1D6754)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF3A816C)
val onPrimaryContainerLight = Color(0xFFF5FFF9)
val secondaryLight = Color(0xFF4A645A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE9DD)
val onSecondaryContainerLight = Color(0xFF506A60)
val tertiaryLight = Color(0xFF5C558A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF756EA5)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF7FAF7)
val onBackgroundLight = Color(0xFF191C1B)
val surfaceLight = Color(0xFFF7FAF7)
val onSurfaceLight = Color(0xFF191C1B)
val surfaceVariantLight = Color(0xFFDBE5DF)
val onSurfaceVariantLight = Color(0xFF3F4945)
val outlineLight = Color(0xFF6F7974)
val outlineVariantLight = Color(0xFFBFC9C3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D312F)
val inverseOnSurfaceLight = Color(0xFFEFF1EE)
val inversePrimaryLight = Color(0xFF8ED4BC)
val surfaceDimLight = Color(0xFFD8DBD8)
val surfaceBrightLight = Color(0xFFF7FAF7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF2F4F1)
val surfaceContainerLight = Color(0xFFECEFEB)
val surfaceContainerHighLight = Color(0xFFE6E9E6)
val surfaceContainerHighestLight = Color(0xFFE0E3E0)
val primaryDark = Color(0xFF8ED4BC)
val onPrimaryDark = Color(0xFF00382B)
val primaryContainerDark = Color(0xFF589E87)
val onPrimaryContainerDark = Color(0xFF000906)
val secondaryDark = Color(0xFFB1CDC1)
val onSecondaryDark = Color(0xFF1C352D)
val secondaryContainerDark = Color(0xFF354E45)
val onSecondaryContainerDark = Color(0xFFA3BFB3)
val tertiaryDark = Color(0xFFC8BFFC)
val onTertiaryDark = Color(0xFF30295B)
val tertiaryContainerDark = Color(0xFF918AC3)
val onTertiaryContainerDark = Color(0xFF06002A)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101413)
val onBackgroundDark = Color(0xFFE0E3E0)
val surfaceDark = Color(0xFF101413)
val onSurfaceDark = Color(0xFFE0E3E0)
val surfaceVariantDark = Color(0xFF3F4945)
val onSurfaceVariantDark = Color(0xFFBFC9C3)
val outlineDark = Color(0xFF89938E)
val outlineVariantDark = Color(0xFF3F4945)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E3E0)
val inverseOnSurfaceDark = Color(0xFF2D312F)
val inversePrimaryDark = Color(0xFF206A56)
val surfaceDimDark = Color(0xFF101413)
val surfaceBrightDark = Color(0xFF363A38)
val surfaceContainerLowestDark = Color(0xFF0B0F0D)
val surfaceContainerLowDark = Color(0xFF191C1B)
val surfaceContainerDark = Color(0xFF1D201F)
val surfaceContainerHighDark = Color(0xFF272B29)
val surfaceContainerHighestDark = Color(0xFF323634)






